[package]
name = "pnacl-hello-world"
version = "0.0.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]

[dependencies.ppapi]
git = "https://github.com/DiamondLovesYou/rust-ppapi.git"

[[bin]]
name = "pnacl-hello-world"
